### ISSUE TITLE
【エラー】アプリを起動するとエラーとなります

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/board-app#1]
↓のエラーがノブハラさんの環境で発生しないということは`eslint-plugin-unused-imports`をうまくローカルインストールできていないかと思います🤔（誤ってグローバルインストールしたとか？）
```
Failed to compile.

[eslint] Failed to load plugin 'unused-imports' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-unused-imports'
Require stack:
- /Users/mizushimayuuki/Workspace/Projects/RaiseTech/Temp/board-app/node_modules/react-scripts/config/__placeholder__.js
ERROR in [eslint] Failed to load plugin 'unused-imports' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-unused-imports'
Require stack:
- /Users/mizushimayuuki/Workspace/Projects/RaiseTech/Temp/board-app/node_modules/react-scripts/config/__placeholder__.js

webpack compiled with 1 error
No issues found.
```

上記を解消すると別のエラーが発生します（抜粋）
```
Failed to compile.

[eslint] 
src/App.tsx
  Line 0:  Parsing error: Cannot read file '/users/nobuhara.yuki/desktop/board-ts-app/board-app/tsconfig.json'

webpack compiled with 1 error
```

eslintのparserOptions.projectのパスの指定が誤っているようです👀
ノブハラさんの環境に依存したパスの設定の仕方になっていそうなので、相対パスで指定すると良いと思います🙆‍♂️

**Comment by yuki96422** [comment]
ローカルへのインストール方法はどのようにすれば良いのでしょうか？

npm install --save-dev eslint-plugin-unused-imports　では実行できませんでした。

表示されたエラーは以下です

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/unused-imports - Not found
npm ERR! 404 
npm ERR! 404  'unused-imports@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nobuhara.yuki/.npm/_logs/2022-10-25T22_05_33_204Z-debug-0.log

**Comment by mizushima1226** [comment]
ん〜〜
実行しているコマンドはだいたいgithubのreadmeの通りなのでうまくいくはずなのですが、、、
以下のコマンドで対象のライブラリが存在するかチェックすることができます💡
（結果が帰って来れば存在するということ）
```
% npm info eslint-plugin-unused-imports

eslint-plugin-unused-imports@2.0.0 | MIT | deps: 1 | versions: 17
Report and remove unused es6 modules
https://github.com/sweepline/eslint-plugin-unused-imports

keywords: eslint, eslintplugin, eslint-plugin, import, unused, modules, autofix

dist
.tarball: https://registry.npmjs.org/eslint-plugin-unused-imports/-/eslint-plugin-unused-imports-2.0.0.tgz
.shasum: d8db8c4d0cfa0637a8b51ce3fd7d1b6bc3f08520
.integrity: sha512-3APeS/tQlTrFa167ThtP0Zm0vctjr4M44HMpeg1P4bK6wItarumq0Ma82xorMKdFsWpphQBlRPzw/pxiVELX1A==
.unpackedSize: 11.1 kB

dependencies:
eslint-rule-composer: ^0.3.0 

maintainers:
- sweepline <mikkel@holmerp.dk>

dist-tags:
latest: 2.0.0  

published 11 months ago by sweepline <mikkel@holmerp.dk>
```

https://github.com/sweepline/eslint-plugin-unused-imports
↑githubのreadmeに記載してあるコマンドをコピペで実行してみる、とかも1つの手ですね🤔

**Comment by yuki96422** [comment]
githubのreadmeに記載してあるコマンドをコピペで実行してみた結果、おそらくインストールすることができました
npm info eslint-plugin-unused-importsを実行した結果、ライブラリがあることを確認しましたm(_ _)m

**Comment by mizushima1226** [comment]
> githubのreadmeに記載してあるコマンドをコピペで実行してみた結果、おそらくインストールすることができました

package.jsonにインストールしたライブラリの差分出ているはずなのでそちらで確認できるかと思います〜（参考まで）
