### ISSUE TITLE
【改善】未入力でも投稿できてしまいます

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/board-app#2]
タイトルの通りです〜
入力値のチェック処理（バリデーション）はどのアプリでも必ずやることなので
このアプリでも同様に最低限のバリデーションは実装しておくと良いと思います👍

**Comment by yuki96422** [comment]
こちらは未着手です。今週が本業が終日詰まっているため、おそらく週末に着手します（隙間時間あれば平日に着手予定です）

**Comment by yuki96422** [comment]
ありがとうございます。こちらもバリデーションの実装完了しました。（エラーのポップアップが出るようにしています）

**Comment by mizushima1226** [comment]
確認しました〜
