### ISSUE TITLE
【改善】reduxのactionがanyを許容しているので型安全にしたい

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/board-app#3]
addPostの引数のpayloadがany型となっているかと思います

https://github.com/yuki96422/board-app/blob/b13b3b59600e20560ee67156eca51c8ff91db82b/src/features/Posts.ts#L18-L22

これだとaddPostでどんなデータ型も許容してしまいコンパイルエラーとならないのでバグの温床となります〜💡

以下を参考にpayloadに型指定すると良いと思います👍
https://redux-toolkit.js.org/usage/usage-with-typescript#createslice

型を指定した上で、addPostをdispatchしている箇所でPostData型ではない引数を指定すると、コンパイルエラーになると思うので
そこまで確認してもらえると、型安全の重要さが体感できるかと思います〜

**Comment by yuki96422** [comment]
引数に型を指定しました。ご確認お願いします！

**Comment by mizushima1226** [comment]
完璧ですっ🚀
