### ISSUE TITLE
PostAreaコンポーネントについて

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/board-app#4]
以下のCSSプロパティは不要そうですがどうでしょう👀

https://github.com/yuki96422/board-app/blob/b13b3b59600e20560ee67156eca51c8ff91db82b/src/components/PostArea.tsx#L39-L40

text-alignはデフォルト値がleftで、
HStackやVStackはflex-containerとなるので💡

---
Inputはコンポーネント化しても良いかもしれませんね〜
背景色の白にしたり、影をつけたりと共通のデザインがあるようなので💡

**Comment by yuki96422** [comment]
ありがとうございます。コンポーネント化しました

**Comment by mizushima1226** [comment]
確認しました〜
