### ISSUE TITLE
PostButtonコンポーネントについて

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/board-app#5]
`PostButton`と具体的な命名しつつ、children受け取っているのでちゃんと汎用性を意識したコンポーネントになっていると思いました👍

命名は`MainButton`くらいの抽象度でいいかもしれません🤔

ここからが本題ですが、このコンポーネントでは`w`と`h`を指定しているので、
そのサイズにしかならないコンポーネントとなっております

ChakraUIのpropsが全部指定できるようなコンポーネントにすると、使用側から自由に設定ができるのでより汎用性の高いコンポーネントになります💡

https://qiita.com/Yametaro/items/814f40d08e9d30584e20
↑の記事がかなり参考になると思うのでtryしてみると良いかもしれません💪
この記事ではchakraui使ってないので一部読み替える必要ありますのでご注意を！

**Comment by yuki96422** [comment]
参考記事を見ながら作成したところ、Propsとして渡せるものと渡せないものがあります。

渡せる⇨name,type,color
渡せない→width,background-color,hover

結果、&で拡張して渡せない物をPropsに定義しましたが「記述量を減らす」という目的は達成していないと思います。

width,background-color,hoverなどの値はJSX.intrinsricElementsの要素内には含まれないのでしょうか？
正しい記述方法をご教示いただけますと幸いです。
※JSX.intrinsricElementsの一覧を探しましたが該当記事がありませんでした

また、ちなみにこのようなissueに対するコメントなどはisuue内でやりとりするもので合っていますか？

プルリクエストのコメントでやりとりするものでしょうか？

**Comment by mizushima1226** [comment]
> この記事ではchakraui使ってないので一部読み替える必要ありますのでご注意を！

ここの読替えが必要な部分ですね〜

> type InputProps = JSX.IntrinsicElements['input']

これはReact標準の`<input />`に指定できるpropsの型になります
今回はChakraUIの`Button`コンポーネントが対象です〜
ので、Buttonコンポーネントのpropsの型に置き換える必要があります💡
この型はChakraUIが提供してくれています〜
確か`ButtonProps`みたいな命名だった気が👀

> また、ちなみにこのようなissueに対するコメントなどはisuue内でやりとりするもので合っていますか？

とりあえずコード書いてみたのであれこれ相談してみたい
とかだったら一旦プルリクあげてコード見ながら
ってパターンもありですね〜

プロジェクトの運用によりけりだと思いますが、issue立てて、対応方針など意見出し合って方針固めて
タスク化してプルリク上げる
みたいなざっくりとしたイメージかと〜

**Comment by yuki96422** [comment]
承知しました
でしたら以降はプルリクで展開します
ご回答ありがとうございました

**Comment by mizushima1226** [comment]
↓がmergeされたのでcloseしておきますね〜
https://github.com/yuki96422/board-app/pull/9
